function homelive(){
document.write("<div class=\"col-12 btn btn btn-dark text-light mb-1\">Wednesday, 2022-11-23<\/div>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>11:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Morocco vs Croatia<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>14:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Germany vs Japan<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>17:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Spain vs Costa Rica<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>20:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Belgium vs Canada<\/div><\/div><\/div><\/div><\/a>");
}

function schedule(){
document.write("<div class=\"col-12 btn btn btn-dark text-light mb-1\">Thursday, 2022-11-24<\/div>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>11:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Switzerland vs Cameroon<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>14:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Uruguay vs Korea Republic<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>17:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Portugal vs Ghana<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>20:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Brazil vs Serbia<\/div><\/div><\/div><\/div><\/a>");
document.write("<div class=\"col-12 btn btn btn-dark text-light mb-1\">Friday, 2022-11-25<\/div>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>11:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Wales vs Iran<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>14:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Qatar vs Senegal<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>17:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Netherlands vs Ecuador<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>20:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>England vs USA<\/div><\/div><\/div><\/div><\/a>");
document.write("<div class=\"col-12 btn btn btn-dark text-light mb-1\">Saturday, 2022-11-26<\/div>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>11:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Tunisia vs Australia<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>14:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Poland vs Saudi Arabia<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>17:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>France vs Denmark<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>20:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Argentina vs Mexico<\/div><\/div><\/div><\/div><\/a>");
document.write("<div class=\"col-12 btn btn btn-dark text-light mb-1\">Sunday, 2022-11-27<\/div>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>11:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Japan vs Costa Rica<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>14:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Belgium vs Morocco<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>17:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Croatia vs Canada<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>20:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Spain vs Germany<\/div><\/div><\/div><\/div><\/a>");
document.write("<div class=\"col-12 btn btn btn-dark text-light mb-1\">Monday, 2022-11-28<\/div>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>11:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Cameroon vs Serbia<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>14:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Korea Republic vs Ghana<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>17:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Brazil vs Switzerland<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>20:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Portugal vs Uruguay<\/div><\/div><\/div><\/div><\/a>");
document.write("<div class=\"col-12 btn btn btn-dark text-light mb-1\">Tuesday, 2022-11-29<\/div>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>16:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Netherlands vs Qatar<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>16:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Ecuador vs Senegal<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>20:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Iran vs USA<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>20:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Wales vs England<\/div><\/div><\/div><\/div><\/a>");
document.write("<div class=\"col-12 btn btn btn-dark text-light mb-1\">Wednesday, 2022-11-30<\/div>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>16:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Tunisia vs France<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>16:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Australia vs Denmark<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>20:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Poland vs Argentina<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>20:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Saudi Arabia vs Mexico<\/div><\/div><\/div><\/div><\/a>");
document.write("<div class=\"col-12 btn btn btn-dark text-light mb-1\">Thursday, 2022-12-1<\/div>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>16:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Croatia vs Belgium<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>16:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Canada vs Morocco<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>20:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Japan vs Spain<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>20:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Costa Rica vs Germany<\/div><\/div><\/div><\/div><\/a>");
document.write("<div class=\"col-12 btn btn btn-dark text-light mb-1\">Friday, 2022-12-2<\/div>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>16:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Korea Republic vs Portugal<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>16:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Ghana vs Uruguay<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>20:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Cameroon vs Brazil<\/div><\/div><\/div><\/div><\/a>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-1.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"worldcup\"><\/div><div class='px-3 my-auto'><span>20:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Serbia vs Switzerland<\/div><\/div><\/div><\/div><\/a>");
}

function formula1(){
document.write("<div class=\"col-12 btn btn btn-dark text-light mb-1\">Saturday, 2022-11-20<\/div>");
document.write("<a class='text-decoration-none nav-link2' href='\/2022\/08\/football-10.html' target='_blank'><div class='d-flex bg-game my-2 btn btn btn-secondary text-start position-relative'><div class=\"F1\"><\/div><div class='px-3 my-auto'><span>13:00<\/span><\/div><div class='col-8 fs-7 px-2 my-auto'><div class='my-auto'><div class='col-11'>Formula 1 2022 - United Arab Emirates GP<\/div><\/div><\/div><\/div><\/a>");
}
